DEFAULT_PORT = "COM10"
DEFAULT_TRIAL_AMOUNT = 25
DEFAULT_DISPLAY_RATE = 0.25  # seconds
DEFAULT_SOFTWARE_STREAM_NAME = "PsychoPyMarkers"
DEFAULT_TRIG = 3

DEFAULT_SOFTWARE_CH_NAME = "PsychoPyMarkers_SoftwareMarker"
DEFAULT_HARDWARE_CH_NAME = "WS-default_TRG"
DEFAULT_TIMESTAMP_CH_NAME = "lsl_timestamp"
DEFAULT_TARGETS = ["mmbts", "lightdiode"]

DEFAULT_DURATION = 10
DEFAULT_STREAM_NAME = "WS-default"
DEFAULT_OUTPUT_PATH = "."

DEFAULT_STREAM_NAME = "WS-default"
DEFAULT_OFFSET_VALUE = 0.0
