DEFAULT_PORT = "COM8"
DEFAULT_TRIAL_AMOUNT = 10
DEFAULT_DISPLAY_RATE = 0.5  # seconds
DEFAULT_SOFTWARE_STREAM_NAME = "PsychoPyMarkers"
DEFAULT_TRIG = 5

DEFAULT_TIMESTAMP_CH_NAME = "lsl_timestamp"
DEFAULT_TARGETS = ["mmbts", "lightdiode"]

DEFAULT_DURATION = 10
DEFAULT_STREAM_NAME = "WS-default"
DEFAULT_OUTPUT_PATH = "."

DEFAULT_OFFSET_VALUE = 0.0
